/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Registro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import modelo.Empleado;
import sql.Conexion;


/**
 *
 * @author fgarcia
 */
public class EmpleVentana extends javax.swing.JFrame {

    /**
     * Creates new form EmpleVentana
     */
    public EmpleVentana() {
        initComponents();
    }

    void mostrarDatos(String valor){
        DefaultTableModel modelo= new DefaultTableModel();
        JTable tabla = new JTable(modelo);
    //    TableRowSorter<TableModel> elQueOrdena = new TableRowSorter<>(modelo);
     //   tbEmple.setRowSorter(elQueOrdena);
    //    tbEmple.setAutoCreateRowSorter(true);

        modelo.addColumn("CODIGO");
        modelo.addColumn("RUT");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("CELULAR");
        modelo.addColumn("EMAIL");
        modelo.addColumn("SUELDO BRUTO");
        modelo.addColumn("EST_CIVIL");
        modelo.addColumn("NOM_DEPTO");
     //codigo,rut,nombre,apellido, celular,email,sueldo_bruto,est_civil,nom_depto
        tbEmple.setModel(modelo);
        String sql="";
        if(valor.equals(""))
            {   sql="select * from usuario01.rqempleado";   }
        if(valor.equals("limpiar"))
            {   sql="SELECT * FROM USUARIO01.RQEMPLEADO where codigo = -1";    }
        else{   sql="SELECT * FROM usuario01.rqempleado";   }
        String []datos = new String [9];
            try {
                Connection conexion = Conexion.getConexion(Registro.nube);
                java.sql.PreparedStatement mostrarTodos;
            mostrarTodos = conexion.prepareStatement(sql);
            ResultSet rs = mostrarTodos.executeQuery();
            
            while(rs.next()){
                datos[0]=rs.getString("CODIGO");
                datos[1]=rs.getString("RUT");
                datos[2]=rs.getString("NOMBRE");
                datos[3]=rs.getString("APELLIDO");
                datos[4]=rs.getString("CELULAR");
                datos[5]=rs.getString("EMAIL");
                datos[6]=rs.getString("SUELDO_BRUTO");
                datos[7]=rs.getString("EST_CIVIL");
                datos[8]=rs.getString("NOM_DEPTO");
                modelo.addRow(datos);
                }
                tbEmple.setModel(modelo);
            } 
            catch (SQLException ex) {
                System.out.println("Error SQL al listar pelicula" +ex.getMessage());
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Codigo = new javax.swing.JLabel();
        Categoria = new javax.swing.JLabel();
        Formato4k = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        botonGrabar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        comboEst = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        txtBuscarCodigoModificar = new javax.swing.JTextField();
        botonBuscarxCodigo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarCodigoEliminar = new javax.swing.JTextField();
        botonEliminarxCodigo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Codigo1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        Codigo2 = new javax.swing.JLabel();
        Codigo3 = new javax.swing.JLabel();
        Codigo4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        Categoria1 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        Codigo5 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        Codigo6 = new javax.swing.JLabel();
        botonMostrarTodas = new javax.swing.JButton();
        comboDep = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmple = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        menuSalir = new javax.swing.JMenuItem();
        Seleccione_BD = new javax.swing.JMenu();
        menuBD_Local = new javax.swing.JMenuItem();
        menuBD_Nube = new javax.swing.JMenuItem();

        Modificar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Modificar.setText("Modificar");
        Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Codigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Codigo.setText("Rut");

        Categoria.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Categoria.setText("Celular");

        Formato4k.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Formato4k.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Formato4k.setText("Est_Civil");
        Formato4k.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        botonGrabar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonGrabar.setText("Agregar");
        botonGrabar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGrabarActionPerformed(evt);
            }
        });

        botonModificar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonLimpiar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonLimpiar.setText("Limpiar");
        botonLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        comboEst.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        comboEst.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "S", "C", "V" }));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel2.setName("Buscar por Código"); // NOI18N

        txtBuscarCodigoModificar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        botonBuscarxCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonBuscarxCodigo.setText("Buscar");
        botonBuscarxCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonBuscarxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarxCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarCodigoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(botonBuscarxCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBuscarxCodigo)
                    .addComponent(txtBuscarCodigoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar por Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel3.setName("Buscar por Código"); // NOI18N

        txtBuscarCodigoEliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        botonEliminarxCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonEliminarxCodigo.setText("Eliminar");
        botonEliminarxCodigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonEliminarxCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarxCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtBuscarCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(botonEliminarxCodigo)
                .addGap(234, 234, 234))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCodigoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminarxCodigo))
                .addGap(24, 24, 24))
        );

        jLabel5.setText("__________________________________________________________________________________________");

        jLabel2.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel2.setText("Administrador de Empleados");

        Codigo1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Codigo1.setText("Código");

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtRut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Codigo2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Codigo3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Codigo3.setText("Apeliido");

        Codigo4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Codigo4.setText("Nombre");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Categoria1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Categoria1.setText("Email");

        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Codigo5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Codigo5.setText("Nom_depto");

        txtSueldo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        Codigo6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Codigo6.setText("Sueldo Bruto");

        botonMostrarTodas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        botonMostrarTodas.setText("Mostrar Empleados");
        botonMostrarTodas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        botonMostrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarTodasActionPerformed(evt);
            }
        });

        comboDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Informatica", "Redes", "Administracion", "Finanzas", "Bienestar" }));

        tbEmple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tbEmple.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "RUT", "NOMBRE", "APELLIDO", "CELULAR", "EMAIL", "SUELDO BRUTO", "EST_CIVIL", "NOMBRE"
            }
        ));
        tbEmple.setComponentPopupMenu(jPopupMenu1);
        tbEmple.setRowHeight(30);
        jScrollPane1.setViewportView(tbEmple);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(botonGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1006, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(548, 548, 548)
                        .addComponent(comboEst, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Codigo4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Codigo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtApellido))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(Codigo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Codigo2)
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Codigo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Codigo6))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(Categoria)
                                                .addGap(215, 215, 215)
                                                .addComponent(Codigo5))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Categoria1)
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Formato4k))
                                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboDep, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(botonMostrarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(414, 414, 414))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Codigo)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Codigo1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botonGrabar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Codigo6)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Categoria)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Codigo3)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Categoria1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Codigo2)
                                .addComponent(Codigo4)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Codigo5))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonLimpiar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comboDep, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Formato4k))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(botonModificar)
                        .addGap(66, 66, 66)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonMostrarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        Archivo.setText("Archivo");
        Archivo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        Archivo.add(menuSalir);

        jMenuBar1.add(Archivo);

        Seleccione_BD.setText("Seleccione_BD");
        Seleccione_BD.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuBD_Local.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuBD_Local.setText("BD_Local");
        menuBD_Local.setName("menuBD_Local"); // NOI18N
        menuBD_Local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBD_LocalActionPerformed(evt);
            }
        });
        Seleccione_BD.add(menuBD_Local);

        menuBD_Nube.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        menuBD_Nube.setText("BD_Nube");
        menuBD_Nube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBD_NubeActionPerformed(evt);
            }
        });
        Seleccione_BD.add(menuBD_Nube);

        jMenuBar1.add(Seleccione_BD);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarActionPerformed

      int fila = tbEmple.getSelectedRow();
      if(fila>=0){
          this.txtCodigo.setEnabled(false);
          txtCodigo.setText(tbEmple.getValueAt(fila, 0).toString());
          txtRut.setText(tbEmple.getValueAt(fila, 1).toString());
          txtNombre.setText(tbEmple.getValueAt(fila, 2).toString());
          txtApellido.setText(tbEmple.getValueAt(fila, 3).toString());
          comboEst.setSelectedItem(tbEmple.getValueAt(fila, 7).toString());
          
          
      }
    }//GEN-LAST:event_ModificarActionPerformed

    private void menuBD_LocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBD_LocalActionPerformed

        Registro.nube=false;
        try {
            Connection conexion = Conexion.getConexion(Registro.nube);
            String query = "SELECT 1 FROM usuario01.RQEMPLEADO";
            PreparedStatement ins = conexion.prepareStatement(query);
            if (ins.execute())           
                javax.swing.JOptionPane.showMessageDialog(this, "Estás conectado a BD Local");
            else
                javax.swing.JOptionPane.showMessageDialog(this, "No hay conexión a BD Local ");
        } 
        catch (Exception e) {
            System.out.println("Error al eliminar " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "No hay conexión a BD Local");
            
    }//GEN-LAST:event_menuBD_LocalActionPerformed
}         

    private void menuBD_NubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBD_NubeActionPerformed

        Registro.nube=true;
        try {
            Connection conexion = Conexion.getConexion(Registro.nube);
            String query = "SELECT 1 FROM usuario01.RQEMPLEADO";
            PreparedStatement ins = conexion.prepareStatement(query);
            if (ins.execute())           
                javax.swing.JOptionPane.showMessageDialog(this, "Estás conectado a BD en la Nube");
            else
                javax.swing.JOptionPane.showMessageDialog(this, "No hay conexión a BD en la Nube");
        } 
        catch (Exception e) {
            System.out.println("Error al eliminar " + e.getMessage());
            javax.swing.JOptionPane.showMessageDialog(this, "No hay conexión a BD en la Nube");
            }
    }//GEN-LAST:event_menuBD_NubeActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed

        System.exit(0);

    }//GEN-LAST:event_menuSalirActionPerformed

    private void botonEliminarxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarxCodigoActionPerformed

        int codigo;
        codigo=Integer.parseInt(this.txtBuscarCodigoEliminar.getText());
        Registro registro = new Registro();
        if(registro.eliminarEmpleado((codigo))){
            javax.swing.JOptionPane.showMessageDialog(this, "Registro Eliminado");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Código no Existe!");
        }
    }//GEN-LAST:event_botonEliminarxCodigoActionPerformed

    private void botonBuscarxCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarxCodigoActionPerformed

        int codigo =Integer.parseInt(
            this.txtBuscarCodigoModificar.getText().trim());
        //ahora a traves del controlador solicitamos el registro
        Empleado empleado = new Registro().buscarPorCodigo(codigo);
        //analizamos si retorno el registro o viene vacio
        if(empleado==null){
            javax.swing.JOptionPane.showMessageDialog(this,"No hay registros para el código: "+codigo);
        }else{
            //"desseteamos" el objeto, es decir, el objeto
            //dará la info a cargar en la ventana
            this.txtCodigo.setText(empleado.getCodigo()+"");
            this.txtRut.setText(empleado.getRut()+"");
            this.txtNombre.setText(empleado.getNombre()+"");
            this.txtApellido.setText(empleado.getApellido()+"");
            
            this.txtCelular.setText(empleado.getCelular()+"");
            this.txtEmail.setText(empleado.getEmail()+"");
            
            this.txtSueldo.setText(empleado.getSueldo()+"");
            this.txtCodigo.setEnabled(false);
            String comboEst = empleado.getEstadoc();
            switch (comboEst) {
                case "S":
                this.comboEst.setSelectedIndex(1);
                break;
                case "C":
                this.comboEst.setSelectedIndex(2);
                break;
                case "V":
                this.comboEst.setSelectedIndex(3);
                break;
                default:
                this.comboEst.setSelectedIndex(0);
            }
            
            
            String comboDep= empleado.getDpto();
            switch (comboDep){
                case "Informatica":
                    this.comboDep.setSelectedIndex(1); break;
                case "Redes":
                    this.comboDep.setSelectedIndex(2); break;
                    case "Administracion":
                    this.comboDep.setSelectedIndex(3); break;
                    case "Finanzas":
                    this.comboDep.setSelectedIndex(4); break;
                    case "Bienestar":
                    this.comboDep.setSelectedIndex(5); break;
                    default:
                    this.comboDep.setSelectedIndex(0);      
            }
            
            
        }
    }//GEN-LAST:event_botonBuscarxCodigoActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed

        txtNombre.setText("");
        txtApellido.setText("");
        txtCodigo.setText("");
        txtRut.setText("");
        txtBuscarCodigoModificar.setText("");
        txtBuscarCodigoEliminar.setText("");
        comboEst.setSelectedIndex(0);
        txtCelular.setText("");
        txtEmail.setText("");
        txtSueldo.setText("");
        comboDep.setSelectedIndex(0);
        mostrarDatos("limpiar");
        this.txtCodigo.setEnabled(true);
        (txtCodigo).requestFocus(); // deja el cursor en la casilla deseada
    }//GEN-LAST:event_botonLimpiarActionPerformed

    private void botonMostrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarTodasActionPerformed

        mostrarDatos("");
    }//GEN-LAST:event_botonMostrarTodasActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed

        Empleado empleado = new Empleado();
        boolean datosmalos=false;

        try {

            int codigo = Integer.parseInt(this.txtCodigo.getText().trim());
            empleado.setCodigo(codigo);
            empleado.setRut(this.txtRut.getText().trim());
            
            empleado.setApellido(this.txtApellido.getText().trim());
            
            int celular = Integer.parseInt(this.txtCelular.getText().trim());
            empleado.setCelular(celular);
            
            empleado.setEmail(this.txtEmail.getText().trim());
            
            String sueldo = this.txtSueldo.getText().trim();
            if(Integer.parseInt(sueldo)>120000)
            empleado.setSueldo(Integer.parseInt(sueldo));
            else
            datosmalos=true;
            

             empleado.setEstadoc(this.comboEst.getSelectedItem().toString());
             empleado.setDpto(this.comboDep.getSelectedItem().toString()); 

            String nombre = this.txtNombre.getText().trim();
            if(nombre.length()>0)                               //validar nombre
            empleado.setNombre(nombre);
            else
            datosmalos=true;
            this.txtNombre.setEnabled(false);
            
            
        }
        catch (Exception e) {
            datosmalos =true;
        }
        if(!datosmalos) {
            if (Registro.modificarEmpleado(empleado))
            javax.swing.JOptionPane.showMessageDialog(this, "Registro Modificado");
            else
            javax.swing.JOptionPane.showMessageDialog(this, "¡Código ya Existe!!!");
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Datos mal Ingresados");
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGrabarActionPerformed

        Empleado empleado = new Empleado();
        boolean datosmalos=false;
        try {
            String codigo = this.txtCodigo.getText().trim();
            if(validarInput(codigo,0,100))
            empleado.setCodigo(Integer.parseInt(codigo));    //Validar 
            else
            datosmalos=true;
           
            String rut = this.txtRut.getText().trim();
            if(rut.length()>0)empleado.setRut(rut);
            else datosmalos=true;
            
            String nombre = this.txtNombre.getText().trim();
            if(nombre.length()>0)                               //validar nombre
            empleado.setNombre(nombre);
            else
            datosmalos=true;
            
            String apellido= this.txtApellido.getText().trim();
            if(apellido.length()>0) 
                empleado.setApellido(apellido);
            else datosmalos=true;
            
            String celular= this.txtCelular.getText().trim();
            if(celular.length()==9)
                empleado.setCelular(Integer.parseInt(celular));
            else
                datosmalos=true;
            
            empleado.setEmail(this.txtEmail.getText().trim());
            
            String sueldo = this.txtSueldo.getText().trim();
            if(Integer.parseInt(sueldo)>=120000)
            empleado.setSueldo(Integer.parseInt(sueldo));
            else
            datosmalos=true;
            
            empleado.setEstadoc(this.comboEst.getSelectedItem().toString());
            empleado.setDpto(this.comboDep.getSelectedItem().toString());
           
        }
        catch (Exception e) {
            datosmalos =true;
        }
        
        if(!datosmalos) {
            if (Registro.agregarEmpleado(empleado))
            javax.swing.JOptionPane.showMessageDialog(this, "Registro Grabado");
            else
            javax.swing.JOptionPane.showMessageDialog(this, "¡Error en los datos ingresados!!!");
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Datos mal Ingresados");
        }
    }//GEN-LAST:event_botonGrabarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleVentana().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JLabel Categoria;
    private javax.swing.JLabel Categoria1;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Codigo1;
    private javax.swing.JLabel Codigo2;
    private javax.swing.JLabel Codigo3;
    private javax.swing.JLabel Codigo4;
    private javax.swing.JLabel Codigo5;
    private javax.swing.JLabel Codigo6;
    private javax.swing.JLabel Formato4k;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenu Seleccione_BD;
    private javax.swing.JButton botonBuscarxCodigo;
    private javax.swing.JButton botonEliminarxCodigo;
    private javax.swing.JButton botonGrabar;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonMostrarTodas;
    private javax.swing.JComboBox<String> comboDep;
    private javax.swing.JComboBox<String> comboEst;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuBD_Local;
    private javax.swing.JMenuItem menuBD_Nube;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JTable tbEmple;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscarCodigoEliminar;
    private javax.swing.JTextField txtBuscarCodigoModificar;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables

  //Validador genérico de int
  public boolean validarInput(String input, int inf, int sup) {
        try {
            int x=Integer.parseInt(input);
            if((x >= inf) && (x <= sup)) 
                return true;
            else{
                System.err.println("Debe ingresar un número entero entre " +inf+" y "+sup);
                return false;
            }
            }
        catch(Exception e) {
            System.err.println("Debe ingresar un Número, entre " +inf+" y "+sup);
            return false;
        }
    }
}
